In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv("nba.csv")
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [5]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [7]:
df['College'].fillna("No College", inplace=True)
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
df.dropna(inplace=True)
df

/tmp/ipykernel_19512/698351679.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['College'].fillna("No College", inplace=True)
/tmp/ipykernel_19512/698351679.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4.842684e+06
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,No College,5.000000e+06
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2.239800e+06
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2.433333e+06
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,No College,9.000000e+05
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,No College,2.900000e+06
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,9.472760e+05

In [44]:
df.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [45]:
df.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [46]:
d1 = df['Position'].unique()
d1

array(['PG', 'SF', 'SG', 'PF', 'C'], dtype=object)

In [47]:

# one hot encoding -->  Adds additional columns to the data
dfp = pd.get_dummies(df, columns=["Position"])
dfp

,Name,Team,Number,Age,Height,Weight,College,Salary,Position_C,Position_PF,Position_PG,Position_SF,Position_SG
0,Avery Bradley,Boston Celtics,0.0,25.0,6-2,180.0,Texas,7.730337e+06,False,False,True,False,False
1,Jae Crowder,Boston Celtics,99.0,25.0,6-6,235.0,Marquette,6.796117e+06,False,False,False,True,False
2,John Holland,Boston Celtics,30.0,27.0,6-5,205.0,Boston University,4.842684e+06,False,False,False,False,True
3,R.J. Hunter,Boston Celtics,28.0,22.0,6-5,185.0,Georgia State,1.148640e+06,False,False,False,False,True
4,Jonas Jerebko,Boston Celtics,8.0,29.0,6-10,231.0,No College,5.000000e+06,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,20.0,6-10,234.0,Kentucky,2.239800e+06,False,True,False,False,False
453,Shelvin Mack,Utah Jazz,8.0,26.0,6-3,203.0,Butler,2.433333e+06,False,False,True,False,False
454,Raul Neto,Utah Jazz,25.0,24.0,6-1,179.0,No College,9.000000e+05,False,False,True,False,False
455,Tibor Pleiss,Utah Jazz,21.0,26.0,7-3,256.0,No College,2.900000e+06,True,False,False,False,False
456,Jeff Withey,Utah Jazz,24.0,26.0,7-0,231.0,Kansas,9.472760e+05,True,False,False,False,False

In [48]:
df['Position'] = LabelEncoder().fit_transform(df['Position'])
df.head(20)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,2,25.0,6-2,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,3,25.0,6-6,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,4,27.0,6-5,205.0,Boston University,4.842684e+06
3,R.J. Hunter,Boston Celtics,28.0,4,22.0,6-5,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,1,29.0,6-10,231.0,No College,5.000000e+06
5,Amir Johnson,Boston Celtics,90.0,1,29.0,6-9,240.0,No College,1.200000e+07
6,Jordan Mickey,Boston Celtics,55.0,1,21.0,6-8,235.0,LSU,1.170960e+06
7,Kelly Olynyk,Boston Celtics,41.0,0,25.0,7-0,238.0,Gonzaga,2.165160e+06
8,Terry Rozier,Boston Celtics,12.0,2,22.0,6-2,190.0,Louisville,1.824360e+06
9,Marcus Smart,Boston Celtics,36.0,2,22.0,6-4,220.0,Oklahoma State,3.431040e+06
10,Jared Sullinger,Boston Celtics,7.0,0,24.0,6-9,260.0,Ohio State,2.569260e+06
11,Isaiah Thomas,Boston Celtics,4.0,2,27.0,5-9,185.0,Washington,6.912869e+06
12,Evan Turner,Boston Celtics,11.0,4,27.0,6-7,220.0,Ohio State,3.425510e+06
13,James Young,Boston Celtics,13.0,4,20.0,6-6,215.0,Kentucky,1.749840e+06
14,Tyler Zeller,Boston Celtics,44.0,0,26.0,7-0,253.0,North Carolina,2.616975e+06
15,Bojan Bogdanovic,Brooklyn Nets,44.0,4,27.0,6-8,216.0,No College,3.425510e+06
16,Markel Brown,Brooklyn Nets,22.0,4,24.0,6-3,190.0,Oklahoma State,8.450590e+05
17,Wayne Ellington,Brooklyn Nets,21.0,4,28.0,6-4,200.0,North Carolina,1.500000e+06
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,4,21.0,6-7,220.0,Arizona,1.335480e+06
19,Jarrett Jack,Brooklyn Nets,2.0,2,32.0,6-3,200.0,Georgia Tech,6.300000e+06

In [49]:
# dummy encoding
dummyEncode = pd.get_dummies(df, columns = ['Position'], drop_first = True)
dummyEncode

,Name,Team,Number,Age,Height,Weight,College,Salary,Position_1,Position_2,Position_3,Position_4
0,Avery Bradley,Boston Celtics,0.0,25.0,6-2,180.0,Texas,7.730337e+06,False,True,False,False
1,Jae Crowder,Boston Celtics,99.0,25.0,6-6,235.0,Marquette,6.796117e+06,False,False,True,False
2,John Holland,Boston Celtics,30.0,27.0,6-5,205.0,Boston University,4.842684e+06,False,False,False,True
3,R.J. Hunter,Boston Celtics,28.0,22.0,6-5,185.0,Georgia State,1.148640e+06,False,False,False,True
4,Jonas Jerebko,Boston Celtics,8.0,29.0,6-10,231.0,No College,5.000000e+06,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,20.0,6-10,234.0,Kentucky,2.239800e+06,True,False,False,False
453,Shelvin Mack,Utah Jazz,8.0,26.0,6-3,203.0,Butler,2.433333e+06,False,True,False,False
454,Raul Neto,Utah Jazz,25.0,24.0,6-1,179.0,No College,9.000000e+05,False,True,False,False
455,Tibor Pleiss,Utah Jazz,21.0,26.0,7-3,256.0,No College,2.900000e+06,False,False,False,False
456,Jeff Withey,Utah Jazz,24.0,26.0,7-0,231.0,Kansas,9.472760e+05,False,False,False,False

In [9]:
# one-hot encoding
oneHot = pd.get_dummies(df, columns = ['Position'])
oneHot

,Name,Team,Number,Age,Height,Weight,College,Salary,Position_C,Position_PF,Position_PG,Position_SF,Position_SG
0,Avery Bradley,Boston Celtics,0.0,25.0,6-2,180.0,Texas,7.730337e+06,False,False,True,False,False
1,Jae Crowder,Boston Celtics,99.0,25.0,6-6,235.0,Marquette,6.796117e+06,False,False,False,True,False
2,John Holland,Boston Celtics,30.0,27.0,6-5,205.0,Boston University,4.842684e+06,False,False,False,False,True
3,R.J. Hunter,Boston Celtics,28.0,22.0,6-5,185.0,Georgia State,1.148640e+06,False,False,False,False,True
4,Jonas Jerebko,Boston Celtics,8.0,29.0,6-10,231.0,No College,5.000000e+06,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,20.0,6-10,234.0,Kentucky,2.239800e+06,False,True,False,False,False
453,Shelvin Mack,Utah Jazz,8.0,26.0,6-3,203.0,Butler,2.433333e+06,False,False,True,False,False
454,Raul Neto,Utah Jazz,25.0,24.0,6-1,179.0,No College,9.000000e+05,False,False,True,False,False
455,Tibor Pleiss,Utah Jazz,21.0,26.0,7-3,256.0,No College,2.900000e+06,True,False,False,False,False
456,Jeff Withey,Utah Jazz,24.0,26.0,7-0,231.0,Kansas,9.472760e+05,True,False,False,False,False